global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert-rules.yml

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://lms.skillfactory.ru/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'
