{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"node\"}, instance)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "blackbox-exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average HTTP Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  { "title": "node-exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\"} - node_boot_time_seconds{instance=\"$node\"}"
    }
   ]
  }
 ]
}